### ISSUE TITLE
why it faster than rebar?

### ISSUE THREAD

**Issue by dongyuwei** [platinumthinker/rebar_fast_deps#1]
on https://www.reddit.com/r/erlang/comments/2n9zlx/rebar_fast_deps/ you said "it update dependencies in multithread". So which code do that awesome work? 

Just interested to know, feel free to close this issue, sorry to interrupt you.

**Comment by platinumthinker** [comment]
Sorry for my slow answer.
Multithread processed deps reaslised in module deps.
In function bfs_step i spawn new thread for each dependency.
I use this behaviour in modules implementing commands (update, log, etc..)

**Comment by dongyuwei** [comment]
Thank you for your reply :)
